/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jistributed_JistributedClient */

#ifndef _Included_jistributed_JistributedClient
#define _Included_jistributed_JistributedClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jistributed_JistributedClient
 * Method:    calculateNative
 * Signature: (IIIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jistributed_JistributedClient_calculateNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jint)
#if defined(__cplusplus) && defined(JAVA_NATIVE_METHOD_THROW_CLAUSE)
  throw()
#endif
  ;

#ifdef __cplusplus
}
#endif
#endif
